name: Bug Report
description: Create a report that will help us resolve an issue.
labels:
  - Bug

body:
  - type: markdown
    attributes:
      value: |-
        Please fill out the following form to the best of your ability.
        The better you fill this out, the faster we can resolve the problem.

  - type: dropdown
    attributes:
      label: Server Implementation
      description: >-
        Which server implementation are you using? If your server implementation
        is not listed, we do not provide support for it.
      multiple: false
      options:
        - Spigot
        - Paper
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Server Version
      description: >-
        Which server version are you using? If your version is not listed, we do
        not provide support for it.
      multiple: false
      options:
        - 1.8.8
        - 1.9.4
        - 1.10.2
        - 1.11.2
        - 1.12.2
        - 1.13.2
        - 1.14.4
        - 1.15.2
        - 1.16.5
        - 1.17.1
        - 1.18.2
        - 1.19.1
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce this behaviour
      placeholder: |-
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    attributes:
      label: latest log file (if applicable)
      description: >-
        Please upload your '/logs/latest.log' file to a paste service and post
        the link here.

  - type: textarea
    attributes:
      label: JoinCommands Version
      description: >-
        Please run the command '/about JoinCommands' on your server and post the output
        here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: You can provide additional context below.
