## Default Configuration for Join Commands
## BungeeCord Version

# Debug Mode.
# Should be false unless you are testing a bug.
# Default: false
debug-mode: false

# Set this to true to disable player data files.
# Using this option will cause problems with the 'first-join-only' options.
# Default: false
disable-player-data: false

# To disable all proxy join commands, set the value to 'proxy-join-commands: {}'
proxy-join-commands:
  # A command ID can be any valid YML section string, but they must all be different
  # The ID for this command is 'exampleOneProxy'.
  # Command IDs are only used internally at this time and server no other purpose.
  exampleOneProxy:
    # This command will only run if the player has the 'always.survival' permission.
    permission: "always.survival"

    first-join-only: false

    # Delay for proxy is in seconds.
    delay: 5

    # Valid Placeholders:
    # - {player} - The name of the player that joined
    #
    # Valid Prefixes:
    # - no prefix - Execute the command as the proxy console (e.g. "eco give {player} 100")
    # - [PLAYER] - Execute the command as the proxy player (e.g. "[PLAYER]kit tools")
    command-list:
      - "[PLAYER]server survival"

  exampleProxy2:
    permission: "" # Use an empty string to disable the permission check.
    first-join-only: true # This command will only run the first time that JoinCommands sees this player.
    delay: 20
    command-list:
      - "send {player} lobby"

# End of File
